CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    unit VARCHAR(50),
    price DECIMAL(19,2) NOT NULL,
    cost_price DECIMAL(19,2) NOT NULL,
    minimum_stock INT NOT NULL DEFAULT 0,
    category_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_product_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE INDEX idx_product_sku ON products(sku);
CREATE INDEX idx_product_name ON products(name);
