CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    movement_type VARCHAR(20) NOT NULL,
    quantity INT NOT NULL,
    reference_no VARCHAR(100),
    note VARCHAR(500),
    movement_at TIMESTAMP NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    updated_at TIMESTAMP,
    status VARCHAR(20) DEFAULT 'APPROVED',
    approved_by VARCHAR(50),
    CONSTRAINT fk_movement_product FOREIGN KEY (product_id) REFERENCES products(id)
);
